#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
"""Pre-render docs/<lang>/index.html so every site language has its own indexable page.

docs/index.html translates itself in the browser from its `T` dictionary. Before these
pages existed, every `?lang=` URL served the same English HTML with a canonical pointing
at the English page, so search engines folded the other four languages into it. Each
generated page carries its own text, `<html lang>`, title, and canonical.

Edit docs/index.html only, then run this script. `--check` fails when a generated page is
out of date; CI runs it.
"""

from __future__ import annotations

import argparse
import html
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS = REPO_ROOT / "docs"
SITE = "https://aqua5230.github.io/usage/"
USE_EN_SHOT = {"en", "ja", "ko"}  # mirrors USE_EN_SHOT in docs/index.html
BANNER = "<!-- Generated by scripts/build_site_pages.py from docs/index.html. Do not edit. -->\n"

LANG_RE = re.compile(r"^  '([\w-]+)': \{$")
ENTRY_RE = re.compile(r"""^    (\w+): (['"])(.*)\2,$""")
ELEMENT_RE = re.compile(r'<(\w+)([^>]*?) data-i18n="(\w+)"([^>]*)>(.*?)</\1>', re.S)
ATTR_TAG_RE = re.compile(r'<[^>]*\sdata-i18n-attr="([\w-]+):(\w+)"[^>]*>')
SHOT_RE = re.compile(r"<img[^>]*\sdata-shot\s[^>]*>")
LOCAL_URL_RE = re.compile(
    r'(\s(?:src|href|data-img-en|data-img-cjk)=")(?!https?:|#|/|data:|mailto:)'
)
SRCSET_RE = re.compile(r'(\ssrcset=")([^"]+)"')


def parse_translations(source: str) -> dict[str, dict[str, str]]:
    block = source.split("const T = {\n", 1)[1].split("\n};\n", 1)[0]
    table: dict[str, dict[str, str]] = {}
    current: dict[str, str] = {}
    for line in block.splitlines():
        if match := LANG_RE.match(line):
            current = table[match[1]] = {}
        elif (match := ENTRY_RE.match(line)) and "\\" not in match[3]:
            current[match[1]] = match[3]
        elif line.strip() != "},":
            raise ValueError(f"cannot parse T entry: {line!r}")
    return table


def set_attr(tag: str, name: str, value: str) -> str:
    new, count = re.subn(rf'(?<=\s){re.escape(name)}="[^"]*"', lambda _: f'{name}="{value}"', tag)
    if count != 1:
        raise ValueError(f"expected one {name}= in {tag[:80]!r}")
    return new


def replace_once(page: str, old: str, new: str) -> str:
    if page.count(old) != 1:
        raise ValueError(f"expected exactly one {old!r} in docs/index.html")
    return page.replace(old, new)


def render(source: str, lang: str, t: dict[str, str]) -> str:
    url = f"{SITE}{lang}/"
    title = html.escape(t["meta_title"])
    page = replace_once(
        source, '<html lang="en">', f'<html lang="{lang}" data-page-lang="{lang}" data-root="../">'
    )
    page = replace_once(page, "<!doctype html>\n", "<!doctype html>\n" + BANNER)
    page = replace_once(page, f'rel="canonical" href="{SITE}"', f'rel="canonical" href="{url}"')
    page = replace_once(
        page, f'property="og:url" content="{SITE}"', f'property="og:url" content="{url}"'
    )
    page = re.sub(r"<title>.*?</title>", lambda _: f"<title>{title}</title>", page, count=1)
    page = re.sub(
        r'<meta property="og:title"[^>]*>', lambda m: set_attr(m[0], "content", title), page
    )
    page = re.sub(
        r'<meta property="og:description"[^>]*>',
        lambda m: set_attr(m[0], "content", html.escape(t["meta_desc"])),
        page,
    )

    def element(match: re.Match[str]) -> str:
        tag, before, key, after, inner = match.groups()
        if f"<{tag}" in inner:
            raise ValueError(f'nested <{tag}> inside data-i18n="{key}"')
        return f'<{tag}{before} data-i18n="{key}"{after}>{t.get(key, inner)}</{tag}>'

    def attribute(match: re.Match[str]) -> str:
        name, key = match[1], match[2]
        return set_attr(match[0], name, html.escape(t[key])) if key in t else match[0]

    def cjk_shot(match: re.Match[str]) -> str:
        tag = match[0]
        src = re.search(r'data-img-cjk="([^"]+)"', tag)
        size = re.search(r'data-size-cjk="(\d+)x(\d+)"', tag)
        if not src or not size:
            raise ValueError(f"data-shot image lacks CJK variant: {tag[:80]!r}")
        tag = set_attr(tag, "src", src[1])
        return set_attr(set_attr(tag, "width", size[1]), "height", size[2])

    page = ELEMENT_RE.sub(element, page)
    page = ATTR_TAG_RE.sub(attribute, page)
    if lang not in USE_EN_SHOT:
        page = SHOT_RE.sub(cjk_shot, page)
    page = LOCAL_URL_RE.sub(r"\1../", page)
    return SRCSET_RE.sub(
        lambda m: m[1] + ", ".join("../" + c.strip() for c in m[2].split(",")) + '"', page
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if a page is out of date")
    check = parser.parse_args().check

    source = (DOCS / "index.html").read_text(encoding="utf-8")
    stale = []
    for lang, table in parse_translations(source).items():
        if lang == "en":
            continue
        path = DOCS / lang / "index.html"
        page = render(source, lang, table)
        if check:
            if not path.is_file() or path.read_text(encoding="utf-8") != page:
                stale.append(str(path.relative_to(REPO_ROOT)))
            continue
        path.parent.mkdir(exist_ok=True)
        path.write_text(page, encoding="utf-8")
        print(f"wrote {path.relative_to(REPO_ROOT)}")
    if stale:
        print(
            f"Out of date: {', '.join(stale)}. Run python3 scripts/build_site_pages.py",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
